version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app  # Mount local frontend directory into the container
    networks:
      - mern-app

  api-server:
    image: api-server
    ports:
      - "5500:5000"
    volumes:
      - ./server:/app  # Mount local backend directory into the container
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
