const FETCH_ALL_QUESTIONS = "FETCH_ALL_QUESTIONS";
const CREATE_QUESTION = "CREATE_QUESTION";
const UPDATE_QUESTION = "UPDATE_QUESTION";
const DELETE_QUESTION_REQUEST ="DELETE_QUESTION_REQUEST";
const AUTHENTICATION = "AUTHENTICATION"
const LOGOUT = "LOGOUT"

export{
    FETCH_ALL_QUESTIONS,
    CREATE_QUESTION,
    UPDATE_QUESTION,
    DELETE_QUESTION_REQUEST,
    AUTHENTICATION,
    LOGOUT,
}